---
language: python
dist: xenial
services: docker

env:
  global:
    - ROLE_NAME: artifactory
  matrix:
    - MOLECULE_DISTRO: centos7

install:
  # Install test dependencies.
  - pip install molecule docker docker-compose pyopenssl

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME mattandes.$ROLE_NAME
  - cd mattandes.$ROLE_NAME

script:
  # Run tests.
  - molecule test -s travisci

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
